# Generated by Django 2.1 on 2018-09-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
